library:
  expert_tool:
    description: >-
      Expert tool to answer general questions given information as context.
      Input is a user question and context information as a long string, output is an answer to the user question.
      {examples}
    prompt_message: |-
      {{question}}
    system_context: |-
      You are an expert in biopharma manufacture deviations.
      You are asked to answer questions about a specific database of deviation incidents, including similar incidents in the past, reasons to classify the incident as recurring, and potential cause of the incident, of which data is given to you.

      When answering the questions, make sure to follow the principles:
      - Use as much context as possible
      - Do not repeat the information from the preliminary answer (if correct) but instead reference & complement it.
      - If applicable, reference the appendix that the full information is shown in e.g. "Table Appendix"
      - If the question is regarding visualisation, reference that the result is shown in the "Visualisation Appendix"
      - Do not mention an appendix if it does not include relevant information
      - Write your answer in markdown format, make sure it is beautiful and easy to read (e.g. use headings, lists, bold, italic, etc.)

      Always try to answer the question.
    prompt_inputs:
      - name: examples
        content: |-
          Example Input: \"User question: Could you find a list of deviation reports?\"
          Example Output: \"There are 21 deviations in the database, please see a list below...\"
  summarizer_tool:
    description: >-
      Summarizer tool to reduce the length of a text to a few sentences.
      Input is a long string, output is a short summary of the input.
      {examples}
    prompt_message: |-
      You are an expert on digital media and music. Given the following user question and provided information:
      "{{text}}"

      Write a concise summary in markdown format answering the user question.
      Follow the following principles:
      - Be concise
      - If applicable, reference the appendix that the full information is shown in e.g. "Table Appendix"
      - If the question is regarding visualisation, reference that the result is shown in the "Visualisation Appendix"
      - Do not mention an appendix if it does not include relevant information
      - Write your answer in markdown format, make sure it is beautiful and easy to read (e.g. use headings, lists, bold, italic, etc.)

      CONCISE SUMMARY:
    prompt_inputs:
      - name: examples
        content: |-
          Example Input: \"This is a long string that I want to summarize. I want to summarize this long string.\"
          Example Output: \"This is a summary of the long string.\"
    system_context: ''
    max_token_length: 4000
  sql_tool:
    description: >-
      "SQL tool to query the structured table containing deviation reports."
      "Input is a question about the data in natural lanaguage, output is a string that contains an SQL query in markdown format, the number of rows the query returns and the first 3 rows."
      {examples}
    prompt_message: |-
      Given the database schema:
      ---
      {{table_schemas}}
      ---
      And the following notes about the tables:
      ---
      {table_notes}
      ---
      Please answer the following user questions with an SQL query:
      {{question}}
    system_context: |-
      You are an expert for this digital media database.

      During answering, the following principles MUST be followed:
      1. Set the language to the markdown code block for each code block. For example, \```sql SELECT * FROM public.Artist``` is SQL.
      2. Use the postgreSQL dialect, i.e. only functions that are supported
      3. DO NOT make any DML statements (INSERT, UPDATE, DELETE, DROP etc.) to the database.
      4. In WHERE clauses use substring comparison to account for unknown string formulations (e.g. album -> LIKE '%album%')
      6. Make sure the final SQL query starts with '```sql' and ends with '```'
      7. Only use field and table names from the provided database schemas
      8. Ensure to include the schema name before the table, for example, \```sql SELECT * FROM public.Artist``` is correct but \```sql SELECT * FROM Artist``` is INCORRECT
    prompt_inputs:
      - name: examples
        content: |-
          Example Input: \"List all incident IDs in the database"
          Example Output: \"`sql SELECT id FROM public.deviations;`, total rows from SQL query: 21, first 3 rows: QE-017420, QE-017517, QE-017522\"
      - name: table_definitions
        content: |-
          public.deviations | Table with all deviation reports; columns include incident ID, whether incident is recurring, incident description, justification for incident severity, summary of findings on similar incident, and cause of the incident. Each incident is a single row
      - name: table_notes
        content: |-
          Table name: public.deviations
          Table description: Table with all deviation reports; columns include incident ID, whether incident is recurring, incident description, justification for incident severity, summary of findings on similar incident, and cause of the incident. Each incident is a single row
    prompt_selection: |-
      Given the following tables:
      ---
      {table_definitions}
      ---
      Please reply only with a comma separated list of the db and the table names.
      Select the tables that can be most useful for answering to the question:
      {{question}}
    system_context_selection: |-
      You are an expert for this deviation report database.
      You define which tables are useful to answer the question of the user.
      Please follow the instructions to answer the questions:
      1. Only reply with a comma separated list of db and table names. For example, "public.deviations"
      2. Only answer with valid table names from the list
      3. Always format the table names to include the database schema, for example "public.deviations", NOT "deviations"
      3. Reply with the least amount of tables necessary for the question
    prompt_validation: |-
      Given the following SQL query:
      {{query}}
      and the following results executing the query with a LIMIT 5:
      {{result}}
      Does the query answer the following question:
      {{question}}

      You must reply in the following format:
      Valid: [yes/no]
      Reason: [your reason for the validation]
    system_context_validation: |-
      You are an expert for this deviaiton report database.
      You should validate that the constructed SQL query is answering the question of the user.
      You must reply in the following format:
      Valid: [yes/no]
      Reason: [your reason for the validation]
    prompt_refinement: |-
      Given the database schema:
      ---
      {{table_schemas}}
      ---
      Given your previous answer and the complaint from the user, please improve the SQL query to answer the question of the user.
      If the SQL query does not contain the database schema before a table, correct it. For example "SELECT * FROM deviations" should be corrected to "SELECT * FROM public.deviations".
      User question: {{question}}
      Previous answer: {{previous_answer}}
      Complaints: {{complaints}}
    nb_example_rows: 3
    validate_empty_results: False
    validate_with_llm: False
    always_limit_query: False
  clarify_tool:
    default_llm: "gpt-4"
    default_fast_llm: "gpt-3.5-turbo"
    description: >-
      Tool to request clarification from the user when the input question is ambiguous or it's unclear which action plan to select.
      If the user poses a question where it is unclear which action plan to select, use this tool to ask the user to clarify the question, thus enabling you to select the correct action plan
    prompt_message: |-
      {{question}}
    system_context: |-
      Your task is to prompt the user to clarify their question, making it easier to understand which action to take.
      When answering the questions, make sure to follow these principles:
      - Be concise
      - Always encourage the user to clarify the question"
      Example:
      input: {input}
      output: {output}
    prompt_inputs:
      - name: input
        content: |-
          We seem prepared for the optimization now, don't we?
      - name: output
        content: |-
          I'm not sure which action to take. Can you clarify your question such that it is easier to understand what action I should
  chain_tool:
    description: Nested meta-agent tool
    prompt_inputs: []
    additional:
      tools:
        - visualizer_tool
        - expert_tool
      action_plans:
        '3':
          name: ''
          description: Sufficient information in chat history, visualize
          actions:
            - - memory
        '4':
          name: ''
          description: Sufficient information in chat history, answer question
          actions:
            - - memory
              - expert_tool

    prompt_message: >-
      Given the chat history and the user question, what action plan would be best to follow?
      Remember to only put out the number of the action plan you want to follow.

      User question: {input}
    system_context: |-
      You are an expert engineer in biopharma manufacture. You need to report and analyze deviation insidences.
      Your goal is to select the right action plan for the question of the user in the fastest way possible, given the chat history.

      Action plans:
      {action_plans}

      Only reply with the number of the action plan you want to follow and nothing else. For example: "0" or "1" or "2" or "3" or "4"
